[package]
name = "valuable_example"
version = "0.1.0"
edition = "2024"

[dependencies]
nutype = { path = "../../nutype", features = ["valuable"] }
valuable = { version = "0.1.1", features = ["derive"] }
